# Generated by Django 3.0.6 on 2022-02-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
