# Generated by Django 4.0.3 on 2022-04-04 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Unactive', 'Unactive'), ('Finished', 'Finished')], max_length=10, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsd', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(choices=[('Carpenter', 'Carpenter'), ('Helper', 'Helper'), ('Electrician', 'Electrician'), ('Plasterer', 'Plasterer'), ('Welder', 'Welder'), ('Plumber', 'Plumber'), ('Glazier', 'Glazier'), ('Mason', 'Mason'), ('Concrete Finisher', 'Concrete Finisher'), ('Painter', 'Painter'), ('Other', 'Other')], max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('spd', models.FloatField(null=True)),
                ('age', models.CharField(max_length=20, null=True)),
                ('wadd', models.CharField(max_length=200, null=True)),
                ('sdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('wcontact', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ada', models.DateField(auto_now_add=True, null=True)),
                ('atim', models.TimeField(auto_now_add=True, null=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.site')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.worker')),
            ],
        ),
    ]
