# Generated by Django 3.0.6 on 2022-02-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Unactive', 'Unactive'), ('Finished', 'Finished')], max_length=10, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, null=True)),
                ('lsd', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('spd', models.FloatField(null=True)),
                ('wadd', models.CharField(max_length=200, null=True)),
                ('wcontact', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=20, null=True)),
                ('amount', models.CharField(max_length=20, null=True)),
                ('sdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.Employe')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ada', models.DateField(auto_now_add=True, null=True)),
                ('atim', models.TimeField(auto_now_add=True, null=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.Site')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.Worker')),
            ],
        ),
    ]
