# Generated by Django 3.0.6 on 2022-02-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=20, null=True)),
                ('amount', models.CharField(max_length=20, null=True)),
                ('employeid', models.CharField(max_length=20, null=True)),
                ('sdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('wid', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, null=True)),
                ('lsd', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('spd', models.FloatField(null=True)),
                ('wadd', models.CharField(max_length=200, null=True)),
                ('wcontact', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Unactive', 'Unactive'), ('Finished', 'Finished')], max_length=10, null=True),
        ),
    ]
