# Generated by Django 4.0.3 on 2022-04-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0002_alter_attendance_ada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admpage.site'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admpage.worker'),
        ),
    ]
