# Generated by Django 3.0.6 on 2022-02-19 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0002_auto_20220218_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='salary',
            name='employeid',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='wid',
        ),
        migrations.AddField(
            model_name='salary',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.Worker'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ada', models.DateField(auto_now_add=True, null=True)),
                ('atim', models.TimeField(auto_now_add=True, null=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.Site')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.Employe'),
        ),
    ]
