# Generated by Django 3.0.6 on 2022-02-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0003_auto_20220219_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='wadd',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='wcontact',
        ),
    ]
