# Generated by Django 3.0.6 on 2022-02-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0004_auto_20220221_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='wadd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='wcontact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
