# Generated by Django 4.0.3 on 2022-04-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0005_grievance'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.employe'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='g_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
