# Generated by Django 3.0.6 on 2022-02-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0005_auto_20220221_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='worker',
        ),
    ]
