# Generated by Django 3.0.6 on 2022-02-22 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0006_remove_salary_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.Worker'),
        ),
    ]
