# Generated by Django 4.0.3 on 2022-04-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0006_grievance_sender_alter_grievance_g_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='complan_chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500, null=True)),
                ('dtim', models.DateTimeField(auto_now_add=True, null=True)),
                ('grieve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.grievance')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.employe')),
            ],
        ),
    ]
