# Generated by Django 4.0.2 on 2022-05-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0007_complan_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='g_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inprogress', 'Inprogress'), ('Invalid', 'Invalid'), ('Finished', 'Finished')], max_length=20, null=True),
        ),
    ]
