# Generated by Django 4.0.3 on 2022-03-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0007_salary_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='sdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
