# Generated by Django 4.0.2 on 2022-05-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0008_alter_grievance_g_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='g_details',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
