# Generated by Django 4.0.2 on 2022-05-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0009_alter_grievance_g_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='sender',
        ),
    ]
