# Generated by Django 4.0.3 on 2022-03-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0009_remove_worker_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
