# Generated by Django 4.0.2 on 2022-05-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0010_remove_grievance_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='g_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
