# Generated by Django 4.0.3 on 2022-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0010_worker_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
