# Generated by Django 4.0.2 on 2022-05-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0011_alter_grievance_g_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complan_chat',
            name='dtim',
        ),
        migrations.AddField(
            model_name='complan_chat',
            name='cdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='complan_chat',
            name='ctim',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
