# Generated by Django 4.0.3 on 2022-03-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0012_remove_worker_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='category',
            field=models.CharField(choices=[('Carpenter', 'Carpenter'), ('Helper', 'Helper'), ('Electrician', 'Electrician'), ('Plasterer', 'Plasterer'), ('Welder', 'Welder'), ('Plumber', 'Plumber'), ('Glazier', 'Glazier'), ('Mason', 'Mason'), ('Concrete Finisher', 'Concrete Finisher'), ('Painter', 'Painter'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
