# Generated by Django 4.0.2 on 2022-05-02 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admpage', '0012_remove_complan_chat_dtim_complan_chat_cdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complan_chat',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admpage.worker'),
        ),
        migrations.AlterField(
            model_name='complan_chat',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
