# Generated by Django 4.0.2 on 2022-05-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admpage', '0013_complan_chat_worker_alter_complan_chat_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complan_chat',
            name='worker',
        ),
        migrations.AlterField(
            model_name='complan_chat',
            name='sender',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
