# Generated by Django 4.0.3 on 2022-05-05 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admpage', '0014_remove_complan_chat_worker_alter_complan_chat_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='w_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
